name: Bug Report
description: Report a bug in the library code
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for reporting a bug. Please fill out the details below.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Brief description of the bug
      placeholder: "Store.get/1 crashes when using custom provider"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. Call LLMModels.Store.get(:custom_provider)
        2. Observe crash
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens? Include error messages.
    validations:
      required: true

  - type: input
    id: elixir-version
    attributes:
      label: Elixir Version
      placeholder: "1.15.7"
    validations:
      required: true

  - type: input
    id: otp-version
    attributes:
      label: OTP Version
      placeholder: "26.1"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "macOS 14.0, Ubuntu 22.04, etc."
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
    validations:
      required: false
