name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Suggest improvements to the library.

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: Brief description of the feature
      placeholder: "Add support for filtering models by vision capability"
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why do you need this? What problem does it solve?
      placeholder: "I need to find all models that can process images for my app"
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: |
        Add a filter option:
        LLMModels.filter(vision: true)
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other approaches you've thought about
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
    validations:
      required: false
