#!/bin/bash
set -e

SNAPSHOT_FILE="priv/llm_models/snapshot.json"
OUTPUT_FILE="/tmp/metadata_summary.md"

echo "## 🔄 Model Metadata Update" > "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "This PR updates LLM model metadata from upstream sources." >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

if [ -f "$SNAPSHOT_FILE" ]; then
  PROVIDER_COUNT=$(jq '.providers | length' "$SNAPSHOT_FILE")
  MODEL_COUNT=$(jq '.models | length' "$SNAPSHOT_FILE")
  GENERATED_AT=$(jq -r '.metadata.generated_at' "$SNAPSHOT_FILE")
  
  echo "### 📊 Snapshot Statistics" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
  echo "- **Providers**: $PROVIDER_COUNT" >> "$OUTPUT_FILE"
  echo "- **Models**: $MODEL_COUNT" >> "$OUTPUT_FILE"
  echo "- **Generated**: $GENERATED_AT" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
fi

echo "### 📝 Changed Files" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "\`\`\`" >> "$OUTPUT_FILE"
git diff --stat priv/llm_models/upstream/ priv/llm_models/snapshot.json lib/llm_models/generated/valid_providers.ex >> "$OUTPUT_FILE"
echo "\`\`\`" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo "### 🔍 Review Checklist" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "- [ ] Verify provider counts are reasonable" >> "$OUTPUT_FILE"
echo "- [ ] Check model counts per provider" >> "$OUTPUT_FILE"
echo "- [ ] Review any new providers added" >> "$OUTPUT_FILE"
echo "- [ ] Ensure snapshot metadata is valid" >> "$OUTPUT_FILE"
echo "- [ ] Confirm tests pass" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "🤖 *Automatically generated by [update-metadata workflow](../.github/workflows/update-metadata.yml)*" >> "$OUTPUT_FILE"

echo "✅ Summary generated at $OUTPUT_FILE"
cat "$OUTPUT_FILE"
