#!/bin/bash
set -e

VERSION="$1"
SNAPSHOT_FILE="priv/llm_models/snapshot.json"
OUTPUT_FILE="/tmp/release_notes.md"

echo "## Release v$VERSION" > "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "Automated release with updated LLM model metadata." >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

if [ -f "$SNAPSHOT_FILE" ]; then
  PROVIDER_COUNT=$(jq '.providers | length' "$SNAPSHOT_FILE")
  MODEL_COUNT=$(jq '.models | length' "$SNAPSHOT_FILE")
  GENERATED_AT=$(jq -r '.metadata.generated_at' "$SNAPSHOT_FILE")
  VERSION_NUM=$(jq -r '.metadata.version' "$SNAPSHOT_FILE")
  
  echo "### 📊 Metadata Snapshot" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
  echo "- **Version**: $VERSION_NUM" >> "$OUTPUT_FILE"
  echo "- **Providers**: $PROVIDER_COUNT" >> "$OUTPUT_FILE"
  echo "- **Models**: $MODEL_COUNT" >> "$OUTPUT_FILE"
  echo "- **Generated**: $GENERATED_AT" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
  
  echo "### 🏢 Provider Breakdown" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
  jq -r '.providers | to_entries | .[] | "- **\(.value.name)** (\(.key)): \(.value.base_url // "N/A")"' "$SNAPSHOT_FILE" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
fi

echo "### 📦 Installation" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "\`\`\`elixir" >> "$OUTPUT_FILE"
echo "def deps do" >> "$OUTPUT_FILE"
echo "  [" >> "$OUTPUT_FILE"
echo "    {:llm_models, \"~> $VERSION\"}" >> "$OUTPUT_FILE"
echo "  ]" >> "$OUTPUT_FILE"
echo "end" >> "$OUTPUT_FILE"
echo "\`\`\`" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "🤖 *Automatically generated by [publish-release workflow](../.github/workflows/publish-release.yml)*" >> "$OUTPUT_FILE"

echo "✅ Release notes generated at $OUTPUT_FILE"
cat "$OUTPUT_FILE"
