defmodule LLMModels.Application do
  @moduledoc """
  OTP Application for LLMModels.

  Automatically loads the pre-built snapshot on application start.
  The snapshot is generated by `mix llm_models.build` and packaged
  with the release.
  """

  use Application

  @impl true
  def start(_type, _args) do
    LLMModels.load()
  end
end
