defmodule LLMModels.Packaged do
  @moduledoc """
  Provides access to the packaged base snapshot.

  This is NOT a Source - it returns the pre-processed, version-stable snapshot
  that ships with each release. The snapshot has already been through the full
  ETL pipeline (normalize → validate → merge → enrich → filter → index).

  Sources (ModelsDev, Local, Config) provide raw data that gets merged ON TOP
  of this base snapshot.

  ## Loading Strategy

  Behavior controlled by `:compile_embed` configuration option:
  - `true` - Snapshot embedded at compile-time (zero runtime IO)
  - `false` - Snapshot loaded at runtime from priv directory
  """

  @snapshot_filename "priv/llm_models/snapshot.json"

  @doc """
  Returns the absolute path to the packaged snapshot file.

  ## Returns

  String path to `priv/llm_models/snapshot.json` within the application directory.
  """
  @spec path() :: String.t()
  def path do
    Application.app_dir(:llm_models, @snapshot_filename)
  end

  if Application.compile_env(:llm_models, :compile_embed, false) do
    @compile_path Path.join([Application.app_dir(:llm_models), @snapshot_filename])
    @external_resource @compile_path

    snapshot_content = File.read!(@compile_path)
    # Safe: During compile-time, we control the snapshot content
    # The snapshot is generated by mix llm_models.activate which validates all keys
    @snapshot Jason.decode!(snapshot_content, keys: :atoms)

    @doc """
    Returns the packaged base snapshot (compile-time embedded).

    This snapshot is the pre-processed output of the ETL pipeline and serves
    as the stable foundation for this package version.

    ## Returns

    Fully indexed snapshot map with providers, models, and indexes, or `nil` if not available.
    """
    @spec snapshot() :: map() | nil
    def snapshot, do: @snapshot
  else
    @doc """
    Returns the packaged base snapshot (runtime loaded).

    This snapshot is the pre-processed output of the ETL pipeline and serves
    as the stable foundation for this package version.

    ## Returns

    Fully indexed snapshot map with providers, models, and indexes, or `nil` if not available.
    """
    @spec snapshot() :: map() | nil
    def snapshot do
      case File.read(path()) do
        # Safe: Snapshot file is controlled by mix llm_models.pull
        # All keys are validated during generation before being written
        {:ok, content} -> Jason.decode!(content, keys: :atoms)
        {:error, _} -> nil
      end
    end
  end
end
